version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.0

jobs:
  install-and-lint:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # install dependencies
      - run:
          name: install dependencies
          command: yarn install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Linter
          command: yarn lint

workflows:
  test:
    jobs:
      - install-and-lint
      - cypress/run:
          package-manager: yarn
          cypress-command: 'yarn cy:run'
